In [5]:
import numpy as np
import pandas as pd

In [6]:
from tensorflow.keras.models import model_from_json

In [7]:
json_file = open('model.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)

In [8]:
# load weights into new model
loaded_model.load_weights("model_json.h5")
print("Loaded model from disk")

Loaded model from disk


In [9]:
loaded_model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm (UnifiedLSTM)           (None, 128)               1232896   
_________________________________________________________________
dropout (Dropout)            (None, 128)               0         
_________________________________________________________________
dense (Dense)                (None, 128)               16512     
_________________________________________________________________
dense_1 (Dense)              (None, 64)                8256      
_________________________________________________________________
dense_2 (Dense)              (None, 7)                 455       
Total params: 1,258,119
Trainable params: 1,258,119
Non-trainable params: 0
_________________________________________________________________


In [10]:
X = np.load('X.npy')
Y = np.load('Y.npy')

loaded_model.compile(loss='categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

score = loaded_model.evaluate(X, Y, verbose=0)
print("%s: %.2f%%" % (loaded_model.metrics_names[1], score[1]*100))

accuracy: 90.48%


In [11]:
loaded_model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm (UnifiedLSTM)           (None, 128)               1232896   
_________________________________________________________________
dropout (Dropout)            (None, 128)               0         
_________________________________________________________________
dense (Dense)                (None, 128)               16512     
_________________________________________________________________
dense_1 (Dense)              (None, 64)                8256      
_________________________________________________________________
dense_2 (Dense)              (None, 7)                 455       
Total params: 1,258,119
Trainable params: 1,258,119
Non-trainable params: 0
_________________________________________________________________


In [7]:
descriptors = pd.read_csv('Descriptors.csv', index_col = 0)
descriptors.head()

gender  gender_no output  expression_index       video_name  \
1      F          3     An                 1  927_0216_01.MP4   
2      F          3     An                 2  927_0216_01.MP4   
3      F          3     An                 3  927_0216_01.MP4   
4      F          3     An                 4  927_0216_01.MP4   
5      F          3     An                 5  927_0216_01.MP4   

   start_time_in_sec  end_time_in_sec  start_exp  end_exp  \
1           5.356700         9.481139        161      284   
2           9.883585        14.903150        296      447   
3          14.903150        19.427206        447      582   
4          19.427206        25.077029        582      752   
5          25.077029        29.981168        752      899   

                text_file  kinect_start_frame  kinect_end_frame  
1  20170902_092359_00.txt                 217               312  
2  20170902_092359_00.txt                 322               466  
3  20170902_092359_00.txt                 466               564  
4  20170902_092359_00.txt                 564               699  
5  20170902_092359_00.txt                 699               828

In [16]:
filename = 'Final/927_0216_01.csv'

def load_file(file):
    temp_df = pd.read_csv(file, sep=',')
    video_name = filename.split('/')[1].split('.')[0] +'.MP4'
    #output_value = descriptors.loc[descriptors['video_name']==name +'.MP4']['output'][:1].values[0]
    gender = descriptors.loc[descriptors['video_name']==video_name]['gender'][:1].values[0]
    if gender == 'F':
        temp_df['gender'] = 1
    else:
        temp_df['gender'] = 0
    #temp_df.drop(['Unnamed: 152'], axis=1, inplace=True)
    return temp_df.values

my_data = load_file(filename)

In [17]:
def load_group(file):
    data = load_file(file)
    zeros_data = np.zeros((1864-data.shape[0], 2279))
    print(data.shape)
    data = np.concatenate((zeros_data, data), axis=0)
    #print('Now the shape is:', name, data.shape)
    return data

file = load_group(filename)

(952, 2279)


In [18]:
file.shape

(1864, 2279)

In [19]:
file = file.reshape((1, 1864, 2279))

In [20]:
file

array([[[ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        ...,
        [28.63564213, 57.48912941, 85.86617495, ..., 19.23538406,
         10.04987562,  1.        ],
        [30.41381265, 60.01666435, 89.82204629, ..., 28.0713377 ,
         14.03566885,  1.        ],
        [30.06659276, 59.41380311, 88.68483523, ..., 25.01999201,
         12.        ,  1.        ]]])

In [21]:
#my.data.reshape((792, 2278))
result = loaded_model.predict(file)

In [27]:
np.argmax(result)

0

In [28]:
np.where(result == np.amax(result))

(array([0], dtype=int64), array([0], dtype=int64))

In [29]:
index

(array([0], dtype=int64), array([0], dtype=int64))

In [30]:
index = index[0]
element = 0
if index == 0:
    element = 'Ne'
elif index == 1:
    element = 'Sa' 
elif index == 2:
    element = 'Su' 
elif index == 3:
    element = 'Fe' 
elif index == 4:
    element = 'An' 
elif index == 5:
    element = 'Di'
elif index == 6:
    element = 'Ha' 
print(element)

Ne
